### PR TITLE
Add string validators

### LINKED ISSUE #20: Support string based validation
@mansam what do you think of supporting some form of string based authentication?

It would look something like this:

```python
validation = {
    "foo": 'required|length:5|instanceof:str',
 }
```

which would be the same as:

```python
validation = {
    "foo": [Required, Length(5), InstanceOf(str)]
 }
```

all we would need to do to make this work is map the string to the classes and create a list in the backend and let everything work as normal. Basically a middle layer mapper to convert a string to a list and shove it in between the flow we have now.

what do you think? This would just split by the `|` and anything like `length:5,2` would be the same as `[Length(5,2)]`

### PR DESCRIPTION
**Pull request by josephmancuso**
This PR adds the ability for string based authentication. This PR is still a WIP but this is the foundation of how it will work.

You can now make a validator doing something like:

```python
validation = {
    "foo": 'email|required|length:1,2',
}
```

Closes #20 

## NOTE

I recommend putting this in the next major release and breaking support for anything < Python 3

### CODE REVIEW

**Comment by josephmancuso** [comment]
This PR also adds the ability to do a bit of both validation inside a list using both string and class based validation. A single validation can now be written a few ways:

```python
validation = {
    "foo": 'email|length:1,8|required',
}
```

or 

```python
validation = {
    "foo": [Email(), Length(1,8), Required],
}
```

or 

```python
validation = {
    "foo": ['email|length1,8', Required],
}
```

Notice we can pass in several string arguments as a validator in addition to the normal class based validation

**Comment by josephmancuso** [comment]
We'll also need to explore nested validations with this 🤔 Not entirely sure how that will work. We will need some kind of recursion i would think

**Comment by josephmancuso** [comment]
so single nested validation (primarily the `not.`) are now written like this:

```python
validation = {
    "foo": ['email|not.length1,8', Required],
}
```

just prepending a `not.` in front of it and use dot notation

**Comment by josephmancuso** [comment]
I made some changes and this PR now supports 2.6 and above as well as passes all tests

**Comment by josephmancuso** [comment]
I have to finish adding more tests so don't do anything with this yet

**Comment by mansam** [comment]
I'll have time to give this more attention on Monday, but for now the main thing that jumps out at me is that you run into problems if the parameters of the validators contain any of the symbols you're using as delimiters.  For instance, if you split on |, then you'll break validators with strings containing |. If you're splitting arguments on comma, then you'll get a nonsense result if a parameter contains a comma. This is going to have to be a little more sophisticated in terms of how you do your parsing.

**Comment by josephmancuso** [comment]
@mansam right in that case you won't be able to use string validation for that segment of the validator, you'll have to use a combination like:

```python
validation = {
    "foo": ['email|length1,8|range|0,10', InstanceOf(SomeClass), Pattern(r'some_regex_using_|')],
}
```

**Comment by josephmancuso** [comment]
@mansam also i need to make some slight changes and more testing. 90% of the tests also pass with the str validation but i'm gonna see if we can support more edge cases or at least throw exceptions to warn users

**Comment by josephmancuso** [comment]
Simpler validation definitions for 90% of use cases plus overall developer happiness. Most validations don’t need to check for commas for pipes. At least for any of Masonite developers validations which are real world validation checks. Those rare edge cases won’t have fall back to the star validation, they will just never use it. 

Don’t feel pressured to accept it if you do not want to. I don’t want you to feel like Masonite community is taking over the future of the project. I can take this and release a new package under a different pypi name under the Masonite namespace if you feel that is better for you. I completely that

**Comment by mansam** [comment]
I don't want you to think I hate the idea in https://github.com/mansam/validator.py/pull/21 on the face of it, I just want to see if we can do it without arbitrary caveats in the implementation. That will probably mean a more sophisticated engine for parsing out the strings, or perhaps a different syntax, or both.

**Comment by mansam** [comment]
@josephmancuso If this covers your needs I'll accept it. Does this need any further work?

**Comment by josephmancuso** [comment]
Typing this out as you replied: 

I've been thinking about this PR after the feedback. The more i think about this the more i feel this would actually be better off as a wrapper around this library inside Masonite 🤔 . This way we keep this package as is but applications that need this support could build it in?

what do you think? I don't think we can build this without having some caveats that can be debugged by throwing correct exceptions.

**Comment by mansam** [comment]
That sounds good to me as well. I just didn't want to hold you back unnecessarily.

**Comment by josephmancuso** [comment]
sweet :)

**Pull request closed without merging**
