### PR TITLE
return "must be present" within an array

### LINKED ISSUE #14: Required returns errors in string not in Array
If you check any other validation other than `Required`, it checks and gives errors in the array. 

`{"email": ["failed validation"]}`

When I use `Required` and it returns.

`{"email": "must be present"}`

### PR DESCRIPTION
**Pull request by vaibhavmule**
Closes #14

### CODE REVIEW

**Comment by mansam** [comment]
Looks good, thanks for the bug report and for the PR!

**Comment by vaibhavmule** [comment]
In which version I can see these changes?

**Comment by mansam** [comment]
I have a couple more changes to make over the next day, and then I'll cut a new release.

**Comment by vaibhavmule** [comment]
Okay, thanks

**Comment by mansam** [comment]
@vaibhavmule I just pushed release 1.3.0 to PyPI

**Comment by vaibhavmule** [comment]
Thanks I'm going to use in my new project

**Pull request merged**
